/* Generated by npm run build:cloud. Edit cloudfunctions/api/src and rebuild. */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ../../node_modules/dayjs/dayjs.min.js
var require_dayjs_min = __commonJS({
  "../../node_modules/dayjs/dayjs.min.js"(exports2, module2) {
    !(function(t, e) {
      "object" == typeof exports2 && "undefined" != typeof module2 ? module2.exports = e() : "function" == typeof define && define.amd ? define(e) : (t = "undefined" != typeof globalThis ? globalThis : t || self).dayjs = e();
    })(exports2, (function() {
      "use strict";
      var t = 1e3, e = 6e4, n = 36e5, r = "millisecond", i = "second", s = "minute", u = "hour", a = "day", o = "week", c = "month", f = "quarter", h = "year", d = "date", l = "Invalid Date", $ = /^(\d{4})[-/]?(\d{1,2})?[-/]?(\d{0,2})[Tt\s]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?[.:]?(\d+)?$/, y = /\[([^\]]+)]|YYYY|YY|M{1,4}|D{1,2}|d{1,4}|H{1,2}|h{1,2}|a|A|m{1,2}|s{1,2}|Z{1,2}|SSS/g, M = { name: "en", weekdays: "Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday".split("_"), months: "January_February_March_April_May_June_July_August_September_October_November_December".split("_"), ordinal: function(t2) {
        var e2 = ["th", "st", "nd", "rd"], n2 = t2 % 100;
        return "[" + t2 + (e2[(n2 - 20) % 10] || e2[n2] || e2[0]) + "]";
      } }, m = function(t2, e2, n2) {
        var r2 = String(t2);
        return !r2 || r2.length >= e2 ? t2 : "" + Array(e2 + 1 - r2.length).join(n2) + t2;
      }, v = { s: m, z: function(t2) {
        var e2 = -t2.utcOffset(), n2 = Math.abs(e2), r2 = Math.floor(n2 / 60), i2 = n2 % 60;
        return (e2 <= 0 ? "+" : "-") + m(r2, 2, "0") + ":" + m(i2, 2, "0");
      }, m: function t2(e2, n2) {
        if (e2.date() < n2.date()) return -t2(n2, e2);
        var r2 = 12 * (n2.year() - e2.year()) + (n2.month() - e2.month()), i2 = e2.clone().add(r2, c), s2 = n2 - i2 < 0, u2 = e2.clone().add(r2 + (s2 ? -1 : 1), c);
        return +(-(r2 + (n2 - i2) / (s2 ? i2 - u2 : u2 - i2)) || 0);
      }, a: function(t2) {
        return t2 < 0 ? Math.ceil(t2) || 0 : Math.floor(t2);
      }, p: function(t2) {
        return { M: c, y: h, w: o, d: a, D: d, h: u, m: s, s: i, ms: r, Q: f }[t2] || String(t2 || "").toLowerCase().replace(/s$/, "");
      }, u: function(t2) {
        return void 0 === t2;
      } }, g = "en", D = {};
      D[g] = M;
      var p = "$isDayjsObject", S = function(t2) {
        return t2 instanceof _ || !(!t2 || !t2[p]);
      }, w = function t2(e2, n2, r2) {
        var i2;
        if (!e2) return g;
        if ("string" == typeof e2) {
          var s2 = e2.toLowerCase();
          D[s2] && (i2 = s2), n2 && (D[s2] = n2, i2 = s2);
          var u2 = e2.split("-");
          if (!i2 && u2.length > 1) return t2(u2[0]);
        } else {
          var a2 = e2.name;
          D[a2] = e2, i2 = a2;
        }
        return !r2 && i2 && (g = i2), i2 || !r2 && g;
      }, O = function(t2, e2) {
        if (S(t2)) return t2.clone();
        var n2 = "object" == typeof e2 ? e2 : {};
        return n2.date = t2, n2.args = arguments, new _(n2);
      }, b = v;
      b.l = w, b.i = S, b.w = function(t2, e2) {
        return O(t2, { locale: e2.$L, utc: e2.$u, x: e2.$x, $offset: e2.$offset });
      };
      var _ = (function() {
        function M2(t2) {
          this.$L = w(t2.locale, null, true), this.parse(t2), this.$x = this.$x || t2.x || {}, this[p] = true;
        }
        var m2 = M2.prototype;
        return m2.parse = function(t2) {
          this.$d = (function(t3) {
            var e2 = t3.date, n2 = t3.utc;
            if (null === e2) return /* @__PURE__ */ new Date(NaN);
            if (b.u(e2)) return /* @__PURE__ */ new Date();
            if (e2 instanceof Date) return new Date(e2);
            if ("string" == typeof e2 && !/Z$/i.test(e2)) {
              var r2 = e2.match($);
              if (r2) {
                var i2 = r2[2] - 1 || 0, s2 = (r2[7] || "0").substring(0, 3);
                return n2 ? new Date(Date.UTC(r2[1], i2, r2[3] || 1, r2[4] || 0, r2[5] || 0, r2[6] || 0, s2)) : new Date(r2[1], i2, r2[3] || 1, r2[4] || 0, r2[5] || 0, r2[6] || 0, s2);
              }
            }
            return new Date(e2);
          })(t2), this.init();
        }, m2.init = function() {
          var t2 = this.$d;
          this.$y = t2.getFullYear(), this.$M = t2.getMonth(), this.$D = t2.getDate(), this.$W = t2.getDay(), this.$H = t2.getHours(), this.$m = t2.getMinutes(), this.$s = t2.getSeconds(), this.$ms = t2.getMilliseconds();
        }, m2.$utils = function() {
          return b;
        }, m2.isValid = function() {
          return !(this.$d.toString() === l);
        }, m2.isSame = function(t2, e2) {
          var n2 = O(t2);
          return this.startOf(e2) <= n2 && n2 <= this.endOf(e2);
        }, m2.isAfter = function(t2, e2) {
          return O(t2) < this.startOf(e2);
        }, m2.isBefore = function(t2, e2) {
          return this.endOf(e2) < O(t2);
        }, m2.$g = function(t2, e2, n2) {
          return b.u(t2) ? this[e2] : this.set(n2, t2);
        }, m2.unix = function() {
          return Math.floor(this.valueOf() / 1e3);
        }, m2.valueOf = function() {
          return this.$d.getTime();
        }, m2.startOf = function(t2, e2) {
          var n2 = this, r2 = !!b.u(e2) || e2, f2 = b.p(t2), l2 = function(t3, e3) {
            var i2 = b.w(n2.$u ? Date.UTC(n2.$y, e3, t3) : new Date(n2.$y, e3, t3), n2);
            return r2 ? i2 : i2.endOf(a);
          }, $2 = function(t3, e3) {
            return b.w(n2.toDate()[t3].apply(n2.toDate("s"), (r2 ? [0, 0, 0, 0] : [23, 59, 59, 999]).slice(e3)), n2);
          }, y2 = this.$W, M3 = this.$M, m3 = this.$D, v2 = "set" + (this.$u ? "UTC" : "");
          switch (f2) {
            case h:
              return r2 ? l2(1, 0) : l2(31, 11);
            case c:
              return r2 ? l2(1, M3) : l2(0, M3 + 1);
            case o:
              var g2 = this.$locale().weekStart || 0, D2 = (y2 < g2 ? y2 + 7 : y2) - g2;
              return l2(r2 ? m3 - D2 : m3 + (6 - D2), M3);
            case a:
            case d:
              return $2(v2 + "Hours", 0);
            case u:
              return $2(v2 + "Minutes", 1);
            case s:
              return $2(v2 + "Seconds", 2);
            case i:
              return $2(v2 + "Milliseconds", 3);
            default:
              return this.clone();
          }
        }, m2.endOf = function(t2) {
          return this.startOf(t2, false);
        }, m2.$set = function(t2, e2) {
          var n2, o2 = b.p(t2), f2 = "set" + (this.$u ? "UTC" : ""), l2 = (n2 = {}, n2[a] = f2 + "Date", n2[d] = f2 + "Date", n2[c] = f2 + "Month", n2[h] = f2 + "FullYear", n2[u] = f2 + "Hours", n2[s] = f2 + "Minutes", n2[i] = f2 + "Seconds", n2[r] = f2 + "Milliseconds", n2)[o2], $2 = o2 === a ? this.$D + (e2 - this.$W) : e2;
          if (o2 === c || o2 === h) {
            var y2 = this.clone().set(d, 1);
            y2.$d[l2]($2), y2.init(), this.$d = y2.set(d, Math.min(this.$D, y2.daysInMonth())).$d;
          } else l2 && this.$d[l2]($2);
          return this.init(), this;
        }, m2.set = function(t2, e2) {
          return this.clone().$set(t2, e2);
        }, m2.get = function(t2) {
          return this[b.p(t2)]();
        }, m2.add = function(r2, f2) {
          var d2, l2 = this;
          r2 = Number(r2);
          var $2 = b.p(f2), y2 = function(t2) {
            var e2 = O(l2);
            return b.w(e2.date(e2.date() + Math.round(t2 * r2)), l2);
          };
          if ($2 === c) return this.set(c, this.$M + r2);
          if ($2 === h) return this.set(h, this.$y + r2);
          if ($2 === a) return y2(1);
          if ($2 === o) return y2(7);
          var M3 = (d2 = {}, d2[s] = e, d2[u] = n, d2[i] = t, d2)[$2] || 1, m3 = this.$d.getTime() + r2 * M3;
          return b.w(m3, this);
        }, m2.subtract = function(t2, e2) {
          return this.add(-1 * t2, e2);
        }, m2.format = function(t2) {
          var e2 = this, n2 = this.$locale();
          if (!this.isValid()) return n2.invalidDate || l;
          var r2 = t2 || "YYYY-MM-DDTHH:mm:ssZ", i2 = b.z(this), s2 = this.$H, u2 = this.$m, a2 = this.$M, o2 = n2.weekdays, c2 = n2.months, f2 = n2.meridiem, h2 = function(t3, n3, i3, s3) {
            return t3 && (t3[n3] || t3(e2, r2)) || i3[n3].slice(0, s3);
          }, d2 = function(t3) {
            return b.s(s2 % 12 || 12, t3, "0");
          }, $2 = f2 || function(t3, e3, n3) {
            var r3 = t3 < 12 ? "AM" : "PM";
            return n3 ? r3.toLowerCase() : r3;
          };
          return r2.replace(y, (function(t3, r3) {
            return r3 || (function(t4) {
              switch (t4) {
                case "YY":
                  return String(e2.$y).slice(-2);
                case "YYYY":
                  return b.s(e2.$y, 4, "0");
                case "M":
                  return a2 + 1;
                case "MM":
                  return b.s(a2 + 1, 2, "0");
                case "MMM":
                  return h2(n2.monthsShort, a2, c2, 3);
                case "MMMM":
                  return h2(c2, a2);
                case "D":
                  return e2.$D;
                case "DD":
                  return b.s(e2.$D, 2, "0");
                case "d":
                  return String(e2.$W);
                case "dd":
                  return h2(n2.weekdaysMin, e2.$W, o2, 2);
                case "ddd":
                  return h2(n2.weekdaysShort, e2.$W, o2, 3);
                case "dddd":
                  return o2[e2.$W];
                case "H":
                  return String(s2);
                case "HH":
                  return b.s(s2, 2, "0");
                case "h":
                  return d2(1);
                case "hh":
                  return d2(2);
                case "a":
                  return $2(s2, u2, true);
                case "A":
                  return $2(s2, u2, false);
                case "m":
                  return String(u2);
                case "mm":
                  return b.s(u2, 2, "0");
                case "s":
                  return String(e2.$s);
                case "ss":
                  return b.s(e2.$s, 2, "0");
                case "SSS":
                  return b.s(e2.$ms, 3, "0");
                case "Z":
                  return i2;
              }
              return null;
            })(t3) || i2.replace(":", "");
          }));
        }, m2.utcOffset = function() {
          return 15 * -Math.round(this.$d.getTimezoneOffset() / 15);
        }, m2.diff = function(r2, d2, l2) {
          var $2, y2 = this, M3 = b.p(d2), m3 = O(r2), v2 = (m3.utcOffset() - this.utcOffset()) * e, g2 = this - m3, D2 = function() {
            return b.m(y2, m3);
          };
          switch (M3) {
            case h:
              $2 = D2() / 12;
              break;
            case c:
              $2 = D2();
              break;
            case f:
              $2 = D2() / 3;
              break;
            case o:
              $2 = (g2 - v2) / 6048e5;
              break;
            case a:
              $2 = (g2 - v2) / 864e5;
              break;
            case u:
              $2 = g2 / n;
              break;
            case s:
              $2 = g2 / e;
              break;
            case i:
              $2 = g2 / t;
              break;
            default:
              $2 = g2;
          }
          return l2 ? $2 : b.a($2);
        }, m2.daysInMonth = function() {
          return this.endOf(c).$D;
        }, m2.$locale = function() {
          return D[this.$L];
        }, m2.locale = function(t2, e2) {
          if (!t2) return this.$L;
          var n2 = this.clone(), r2 = w(t2, e2, true);
          return r2 && (n2.$L = r2), n2;
        }, m2.clone = function() {
          return b.w(this.$d, this);
        }, m2.toDate = function() {
          return new Date(this.valueOf());
        }, m2.toJSON = function() {
          return this.isValid() ? this.toISOString() : null;
        }, m2.toISOString = function() {
          return this.$d.toISOString();
        }, m2.toString = function() {
          return this.$d.toUTCString();
        }, M2;
      })(), Y = _.prototype;
      return O.prototype = Y, [["$ms", r], ["$s", i], ["$m", s], ["$H", u], ["$W", a], ["$M", c], ["$y", h], ["$D", d]].forEach((function(t2) {
        Y[t2[1]] = function(e2) {
          return this.$g(e2, t2[0], t2[1]);
        };
      })), O.extend = function(t2, e2) {
        return t2.$i || (t2(e2, _, O), t2.$i = true), O;
      }, O.locale = w, O.isDayjs = S, O.unix = function(t2) {
        return O(1e3 * t2);
      }, O.en = D[g], O.Ls = D, O.p = {}, O;
    }));
  }
});

// cloudfunctions/api/src/index.ts
var index_exports = {};
__export(index_exports, {
  main: () => main
});
module.exports = __toCommonJS(index_exports);
var import_wx_server_sdk = __toESM(require("wx-server-sdk"));
var import_dayjs6 = __toESM(require_dayjs_min());

// ../../server/src/domain/constants.ts
var COURSE_ICON_COLORS = {
  school: "#7B61FF",
  sport: "#26C281",
  math: "#FF9A3D",
  reading: "#FF6B8A",
  music: "#C265F0",
  swimming: "#22C4CC",
  english: "#3E9BFF",
  calligraphy: "#F0A92B",
  generic: "#7C8AA5"
};
var CHILD_AVATAR_OPTIONS = [
  { key: "boy-blue", label: "\u84DD\u8863\u7537\u5B69", color: "#5B8DEF" },
  { key: "boy-cap", label: "\u767D\u5E3D\u7537\u5B69", color: "#6EA0F0" },
  { key: "girl-flower", label: "\u7C89\u8863\u5973\u5B69", color: "#FF8AAE" },
  { key: "girl-bow", label: "\u7D2B\u8863\u5973\u5B69", color: "#B388FF" }
];
var DEFAULT_CHILD_AVATAR = CHILD_AVATAR_OPTIONS[0];
function childAvatarOption(key) {
  return CHILD_AVATAR_OPTIONS.find((item) => item.key === key) ?? DEFAULT_CHILD_AVATAR;
}
var BILLING_SCHEMA_VERSION = 4;
function createId(prefix) {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

// ../../server/src/workspace/empty-snapshot.ts
function createEmptyFamilySnapshot(name = "Uday", avatarKey) {
  const option = childAvatarOption(avatarKey);
  const childId = createId("child");
  const trimmed = name.trim() || "Uday";
  return {
    version: 1,
    billingSchemaVersion: BILLING_SCHEMA_VERSION,
    session: { role: "parent", childId },
    children: [
      {
        id: childId,
        name: trimmed,
        grade: "",
        avatarLabel: trimmed.slice(0, 2),
        avatarColor: option.color,
        avatarKey: option.key
      }
    ],
    courses: [],
    expenses: [],
    goals: [],
    scheduleExceptions: [],
    occurrenceRecords: [],
    charges: [],
    payments: [],
    billingMigrationAudits: []
  };
}

// ../../server/src/domain/billing.ts
var import_dayjs = __toESM(require_dayjs_min());
function currentPeriod() {
  return (0, import_dayjs.default)().format("YYYY-MM");
}

// ../../server/src/domain/schedule.ts
var import_dayjs2 = __toESM(require_dayjs_min());
function occurrencesInRange(courses, start, end, exceptions = []) {
  const startDay = (0, import_dayjs2.default)(start).startOf("day");
  const endDay = (0, import_dayjs2.default)(end).endOf("day");
  const list = [];
  function addOccurrence(course, date, startTime, endTime) {
    const exception = exceptions.find((item) => item.courseId === course.id && item.date === date);
    if ((exception == null ? void 0 : exception.status) === "cancelled") return;
    const effectiveCourse = {
      ...course,
      title: (exception == null ? void 0 : exception.title) ?? course.title,
      location: (exception == null ? void 0 : exception.location) ?? course.location,
      note: (exception == null ? void 0 : exception.note) ?? course.note,
      recurrence: {
        ...course.recurrence,
        startTime: (exception == null ? void 0 : exception.startTime) ?? startTime,
        endTime: (exception == null ? void 0 : exception.endTime) ?? endTime
      }
    };
    list.push({
      id: `${course.id}_${date}`,
      occurrenceId: `occ_${course.id}_${date}`,
      date,
      course: effectiveCourse,
      exception
    });
  }
  for (const course of courses) {
    if (course.archived) continue;
    if (course.recurrence.freq === "dates") {
      for (const slot of course.recurrence.dates ?? []) {
        const slotDate = (0, import_dayjs2.default)(slot.date);
        if (slotDate.isBefore(startDay, "day") || slotDate.isAfter(endDay, "day")) continue;
        addOccurrence(course, slot.date, slot.startTime, slot.endTime);
      }
      continue;
    }
    const recStart = (0, import_dayjs2.default)(course.recurrence.startDate);
    const recEnd = course.recurrence.endDate ? (0, import_dayjs2.default)(course.recurrence.endDate) : null;
    let cursor = startDay.isAfter(recStart) ? startDay : recStart;
    while (!cursor.isAfter(endDay)) {
      const inWindow = !recEnd || !cursor.isAfter(recEnd);
      const weekdayMatch = course.recurrence.freq === "once" ? cursor.isSame(recStart, "day") : course.recurrence.byWeekday.includes(cursor.day());
      if (inWindow && weekdayMatch) {
        const date = cursor.format("YYYY-MM-DD");
        addOccurrence(
          course,
          date,
          course.recurrence.startTime,
          course.recurrence.endTime
        );
      }
      cursor = cursor.add(1, "day");
    }
  }
  for (const exception of exceptions) {
    if (exception.status !== "added") continue;
    const date = (0, import_dayjs2.default)(exception.date);
    if (date.isBefore(startDay, "day") || date.isAfter(endDay, "day")) continue;
    if (list.some((item) => item.id === `${exception.courseId}_${exception.date}`)) continue;
    const course = courses.find((item) => item.id === exception.courseId);
    if (!course || course.archived) continue;
    list.push({
      id: `${course.id}_${exception.date}`,
      occurrenceId: `occ_${course.id}_${exception.date}`,
      date: exception.date,
      exception,
      course: {
        ...course,
        title: exception.title ?? course.title,
        location: exception.location ?? course.location,
        note: exception.note ?? course.note,
        recurrence: {
          ...course.recurrence,
          startTime: exception.startTime ?? course.recurrence.startTime,
          endTime: exception.endTime ?? course.recurrence.endTime
        }
      }
    });
  }
  return list.sort((a, b) => {
    const t = a.course.recurrence.startTime.localeCompare(b.course.recurrence.startTime);
    if (t !== 0) return t;
    return a.course.title.localeCompare(b.course.title, "zh-CN");
  });
}
function occurrencesOnDate(courses, date, exceptions = []) {
  return occurrencesInRange(courses, date, date, exceptions);
}
function toMinutes(time) {
  const [hour, minute] = time.split(":").map(Number);
  return hour * 60 + minute;
}
function busyIntervalsOnDate(courses, date, exceptions = []) {
  return occurrencesOnDate(courses, date, exceptions).map((item) => ({
    start: item.course.recurrence.startTime,
    end: item.course.recurrence.endTime,
    title: item.course.title
  })).sort((a, b) => a.start.localeCompare(b.start));
}
function findBusyConflict(intervals, start, end) {
  if (!start || !end || end <= start) return void 0;
  return intervals.find((item) => start < item.end && end > item.start);
}
function courseParticipantIds(course) {
  var _a;
  return ((_a = course.childIds) == null ? void 0 : _a.length) ? course.childIds : [course.childId];
}
function coursesForParticipants(courses, childIds) {
  const ids = new Set(childIds.filter(Boolean));
  if (!ids.size) return [];
  return courses.filter((course) => courseParticipantIds(course).some((id) => ids.has(id)));
}
function findScheduleConflicts(slots, courses, exceptions = [], exceptCourseId, childIds) {
  const scoped = (childIds == null ? void 0 : childIds.length) ? coursesForParticipants(courses, childIds) : courses;
  const conflicts = [];
  for (const slot of slots) {
    if (!slot.date || !slot.startTime || !slot.endTime || slot.endTime <= slot.startTime) continue;
    const intervals = occurrencesOnDate(scoped, slot.date, exceptions).filter((item) => item.course.id !== exceptCourseId).map((item) => ({
      start: item.course.recurrence.startTime,
      end: item.course.recurrence.endTime,
      title: item.course.title
    }));
    const conflict = findBusyConflict(intervals, slot.startTime, slot.endTime);
    if (conflict) {
      conflicts.push({
        date: slot.date,
        startTime: slot.startTime,
        endTime: slot.endTime,
        title: conflict.title
      });
    }
  }
  return conflicts;
}
function minutesBetween(start, end) {
  if (!start || !end) return 0;
  return toMinutes(end) - toMinutes(start);
}

// ../../server/src/domain/courseSchedule.ts
var import_dayjs3 = __toESM(require_dayjs_min());
function sortedSlots(slots) {
  return [...slots].sort((a, b) => a.date.localeCompare(b.date));
}
function stampCourseDates(course, slots) {
  const dates = sortedSlots(slots);
  course.recurrence.freq = "dates";
  course.recurrence.dates = dates;
  course.recurrence.byWeekday = [];
  if (dates.length) {
    course.recurrence.startDate = dates[0].date;
    course.recurrence.endDate = dates[dates.length - 1].date;
    course.recurrence.startTime = dates[0].startTime;
    course.recurrence.endTime = dates[0].endTime;
  }
}
function expandCourseToDates(course, exceptions = []) {
  if (course.recurrence.freq === "dates") {
    return sortedSlots((course.recurrence.dates ?? []).map((slot) => ({ ...slot })));
  }
  const start = (0, import_dayjs3.default)().startOf("month");
  const end = start.add(11, "month").endOf("month");
  return occurrencesInRange(
    [{ ...course, recurrence: { ...course.recurrence } }],
    start.format("YYYY-MM-DD"),
    end.format("YYYY-MM-DD"),
    exceptions
  ).map((item) => ({
    date: item.date,
    startTime: item.course.recurrence.startTime,
    endTime: item.course.recurrence.endTime
  }));
}
function applyExceptionToCourse(course, exception) {
  var _a, _b;
  const slots = expandCourseToDates(course);
  const index = slots.findIndex((slot) => slot.date === exception.date);
  if (exception.status === "cancelled") {
    if (index >= 0) slots.splice(index, 1);
  } else {
    const next = {
      date: exception.date,
      startTime: exception.startTime ?? ((_a = slots[index]) == null ? void 0 : _a.startTime) ?? course.recurrence.startTime,
      endTime: exception.endTime ?? ((_b = slots[index]) == null ? void 0 : _b.endTime) ?? course.recurrence.endTime
    };
    if (index >= 0) slots[index] = next;
    else slots.push(next);
  }
  stampCourseDates(course, slots);
}
function restoreCourseSlot(course, slot) {
  const slots = expandCourseToDates(course);
  const index = slots.findIndex((item) => item.date === slot.date);
  if (index >= 0) slots[index] = { ...slot };
  else slots.push({ ...slot });
  stampCourseDates(course, slots);
}
function removeCourseSlot(course, date) {
  const slots = expandCourseToDates(course).filter((slot) => slot.date !== date);
  stampCourseDates(course, slots);
}

// ../../server/src/domain/charges.ts
var import_dayjs4 = __toESM(require_dayjs_min());
function occurrenceIdFor(courseId, originDate) {
  return `occ_${courseId}_${originDate}`;
}
function roundMoney(amount) {
  return Math.round((Number(amount) || 0) * 100) / 100;
}
function durationMinutes(startTime, endTime) {
  let minutes = minutesBetween(startTime, endTime);
  if (minutes < 0) minutes += 24 * 60;
  return Math.max(0, minutes);
}
function usageMinutes(startTime, endTime, actualMinutes) {
  if (actualMinutes && actualMinutes > 0) return actualMinutes;
  return durationMinutes(startTime, endTime);
}
function isUsagePriced(course) {
  var _a;
  const mode = (_a = course.billingPolicy) == null ? void 0 : _a.pricingMode;
  return mode === "per_session" || mode === "per_hour";
}
function computeUsageAmount(course, minutes, estimated = false) {
  var _a;
  const amount = Number(course.amount) || 0;
  const mode = (_a = course.billingPolicy) == null ? void 0 : _a.pricingMode;
  if (mode === "per_session") {
    return { amount: roundMoney(amount), estimated: false, source: "session" };
  }
  if (mode === "per_hour") {
    return {
      amount: roundMoney(minutes * amount / 60),
      estimated,
      source: "hour"
    };
  }
  return { amount: 0, estimated: false, source: "session" };
}
function expectedUsageCharge(course, startTime, endTime, actualMinutes) {
  const minutes = usageMinutes(startTime, endTime, actualMinutes);
  const computed2 = computeUsageAmount(course, minutes, actualMinutes == null);
  return {
    ...computed2,
    minutes
  };
}
function occurrenceDateFromCharge(charge, records) {
  var _a;
  return ((_a = records.find((record) => record.id === charge.occurrenceId)) == null ? void 0 : _a.date) ?? charge.occurrenceId.slice(charge.occurrenceId.lastIndexOf("_") + 1);
}
function mondayOf(date) {
  const value = (0, import_dayjs4.default)(date);
  return value.subtract((value.day() + 6) % 7, "day").format("YYYY-MM-DD");
}
function chargeStatementKey(charge, course, records) {
  var _a;
  const date = occurrenceDateFromCharge(charge, records);
  const cycle = ((_a = course.billingPolicy) == null ? void 0 : _a.settlementCycle) ?? "manual";
  if (cycle === "weekly") return `${course.id}:weekly:${mondayOf(date)}`;
  if (cycle === "monthly") return `${course.id}:monthly:${date.slice(0, 7)}`;
  return `${course.id}:manual:${date.slice(0, 7)}`;
}
function statementLabel(cycle, statementKey) {
  const value = statementKey.slice(statementKey.lastIndexOf(":") + 1);
  if (cycle === "weekly") {
    const start = (0, import_dayjs4.default)(value);
    return `${start.format("M\u6708D\u65E5")}\u2013${start.add(6, "day").format("M\u6708D\u65E5")}`;
  }
  return (0, import_dayjs4.default)(`${value}-01`).format("YYYY\u5E74M\u6708");
}
function findChargeForOccurrence(charges, occurrenceId) {
  return charges.find((charge) => charge.occurrenceId === occurrenceId && charge.status !== "reversed");
}
function shouldAccrueUsage(course, status, billable) {
  if (course.source === "temporary") return false;
  return isUsagePriced(course) && status === "completed" && billable;
}

// ../../server/src/workspace/family-workspace.ts
var import_dayjs5 = __toESM(require_dayjs_min());
function computed(fn) {
  return { get value() {
    return fn();
  } };
}
function createFamilyWorkspace(initial) {
  const snapshot = { value: initial };
  const persist = () => {
  };
  const child = computed(
    () => snapshot.value.children.find((c) => c.id === snapshot.value.session.childId) ?? snapshot.value.children[0]
  );
  const childId = computed(() => {
    var _a;
    return ((_a = child.value) == null ? void 0 : _a.id) ?? "";
  });
  const isParentSession = computed(() => snapshot.value.session.role === "parent");
  function belongsToChild(course, targetChildId) {
    var _a;
    const assignedChildIds = ((_a = course.childIds) == null ? void 0 : _a.length) ? course.childIds : [course.childId];
    return assignedChildIds.includes(targetChildId);
  }
  function coursesForChild(targetChildId, includeArchived = false) {
    return snapshot.value.courses.filter(
      (course) => belongsToChild(course, targetChildId) && (includeArchived || !course.archived)
    );
  }
  const courses = computed(() => coursesForChild(childId.value));
  const allCourses = computed(() => coursesForChild(childId.value, true));
  const expenses = computed(
    () => snapshot.value.expenses.filter((e) => e.childId === childId.value)
  );
  const goals = computed(() => snapshot.value.goals.filter((g) => g.childId === childId.value));
  const scheduleExceptions = computed(() => {
    const visibleCourseIds = new Set(allCourses.value.map((course) => course.id));
    return snapshot.value.scheduleExceptions.filter((item) => visibleCourseIds.has(item.courseId));
  });
  const familyCourses = computed(
    () => snapshot.value.courses.filter((course) => !course.archived)
  );
  const familyScheduleExceptions = computed(() => {
    const familyCourseIds = new Set(familyCourses.value.map((course) => course.id));
    return snapshot.value.scheduleExceptions.filter((item) => familyCourseIds.has(item.courseId));
  });
  const charges = computed(
    () => {
      var _a;
      return ((_a = snapshot.value.charges) == null ? void 0 : _a.filter((item) => item.childId === childId.value)) ?? [];
    }
  );
  const payments = computed(
    () => {
      var _a;
      return ((_a = snapshot.value.payments) == null ? void 0 : _a.filter((item) => item.childId === childId.value)) ?? [];
    }
  );
  const occurrenceRecords = computed(() => snapshot.value.occurrenceRecords ?? []);
  const overviewCharges = computed(
    () => isParentSession.value ? snapshot.value.charges ?? [] : charges.value
  );
  const overviewPayments = computed(
    () => isParentSession.value ? snapshot.value.payments ?? [] : payments.value
  );
  const overviewCourses = computed(
    () => isParentSession.value ? familyCourses.value : courses.value
  );
  const overviewExpenses = computed(
    () => isParentSession.value ? snapshot.value.expenses : expenses.value
  );
  const overviewScheduleExceptions = computed(
    () => isParentSession.value ? familyScheduleExceptions.value : scheduleExceptions.value
  );
  const todayItems = computed(
    () => occurrencesOnDate(
      overviewCourses.value,
      (0, import_dayjs5.default)().format("YYYY-MM-DD"),
      overviewScheduleExceptions.value
    )
  );
  const monthOpenAmount = computed(
    () => overviewExpenses.value.filter((e) => e.period === currentPeriod() && e.status !== "paid").reduce((s, e) => s + e.amount, 0)
  );
  function upsertCourse(input) {
    var _a;
    const id = input.id ?? createId("course");
    const existingCourse = snapshot.value.courses.find((course) => course.id === id);
    const assignedChildIds = ((_a = input.childIds) == null ? void 0 : _a.length) ? input.childIds : [childId.value];
    const next = {
      ...input,
      id,
      childId: assignedChildIds[0],
      childIds: assignedChildIds,
      archived: (existingCourse == null ? void 0 : existingCourse.archived) ?? false
    };
    const idx = snapshot.value.courses.findIndex((c) => c.id === id);
    if (idx >= 0) snapshot.value.courses[idx] = { ...snapshot.value.courses[idx], ...next };
    else snapshot.value.courses.push(next);
    const saved = snapshot.value.courses.find((course) => course.id === id);
    if (saved) ensureCourseBilling(saved);
    persist();
    return id;
  }
  function findCourseScheduleConflicts(slots, exceptCourseId, childIds) {
    const participants = (childIds == null ? void 0 : childIds.length) ? childIds : child.value ? [child.value.id] : [];
    return findScheduleConflicts(
      slots,
      coursesForParticipants(overviewCourses.value, participants),
      overviewScheduleExceptions.value,
      exceptCourseId,
      participants
    );
  }
  function archiveCourse(id) {
    const course = snapshot.value.courses.find((c) => c.id === id);
    if (course) course.archived = true;
    persist();
  }
  function restoreCourse(id) {
    const course = snapshot.value.courses.find((c) => c.id === id);
    if (course) course.archived = false;
    persist();
  }
  function removeCourse(id) {
    const course = findCourse(id);
    if (!course) return "not-found";
    snapshot.value.courses = snapshot.value.courses.filter((item) => item.id !== id);
    snapshot.value.scheduleExceptions = snapshot.value.scheduleExceptions.filter(
      (item) => item.courseId !== id
    );
    snapshot.value.occurrenceRecords = (snapshot.value.occurrenceRecords ?? []).filter(
      (item) => item.courseId !== id
    );
    snapshot.value.charges = (snapshot.value.charges ?? []).filter((item) => item.courseId !== id);
    snapshot.value.expenses = snapshot.value.expenses.filter((item) => {
      if (item.courseId !== id) return true;
      if (item.status === "paid") {
        item.courseId = void 0;
        item.chargeIds = [];
        return true;
      }
      return false;
    });
    snapshot.value.payments = (snapshot.value.payments ?? []).filter(
      (item) => snapshot.value.expenses.some((expense) => expense.id === item.expenseId)
    );
    persist();
    return "removed";
  }
  function updateChild(input) {
    const target = snapshot.value.children.find((item) => item.id === input.id);
    if (!target) return;
    if (input.name !== void 0) {
      const name = input.name.trim();
      if (!name) return;
      target.name = name;
      target.avatarLabel = name.slice(0, 2);
    }
    if (input.avatarKey) {
      const option = childAvatarOption(input.avatarKey);
      target.avatarKey = option.key;
      target.avatarColor = option.color;
    }
    persist();
  }
  function addChild(name, avatarKey) {
    const trimmed = name.trim();
    if (!trimmed) return "";
    const option = childAvatarOption(avatarKey);
    const id = createId("child");
    snapshot.value.children.push({
      id,
      name: trimmed,
      grade: "",
      avatarLabel: trimmed.slice(0, 2),
      avatarColor: option.color,
      avatarKey: option.key
    });
    persist();
    return id;
  }
  function removeChild(id) {
    const childIndex = snapshot.value.children.findIndex((item) => item.id === id);
    if (childIndex < 0) return "not-found";
    if (snapshot.value.children.length <= 1) return "last-child";
    const removedCourseIds = /* @__PURE__ */ new Set();
    snapshot.value.courses = snapshot.value.courses.flatMap((course) => {
      var _a;
      const assignedChildIds = ((_a = course.childIds) == null ? void 0 : _a.length) ? course.childIds : [course.childId];
      if (!assignedChildIds.includes(id)) return [course];
      const remainingChildIds = assignedChildIds.filter((childId2) => childId2 !== id);
      if (!remainingChildIds.length) {
        removedCourseIds.add(course.id);
        return [];
      }
      return [{
        ...course,
        childId: remainingChildIds[0],
        childIds: remainingChildIds
      }];
    });
    snapshot.value.scheduleExceptions = snapshot.value.scheduleExceptions.filter((item) => !removedCourseIds.has(item.courseId)).map((item) => {
      var _a;
      if (item.childId !== id) return item;
      const course = snapshot.value.courses.find((candidate) => candidate.id === item.courseId);
      return { ...item, childId: ((_a = course == null ? void 0 : course.childIds) == null ? void 0 : _a[0]) ?? (course == null ? void 0 : course.childId) ?? "" };
    }).filter((item) => Boolean(item.childId));
    snapshot.value.expenses = snapshot.value.expenses.filter(
      (item) => item.childId !== id && (!item.courseId || !removedCourseIds.has(item.courseId))
    );
    snapshot.value.charges = (snapshot.value.charges ?? []).filter(
      (item) => item.childId !== id && !removedCourseIds.has(item.courseId)
    );
    snapshot.value.occurrenceRecords = (snapshot.value.occurrenceRecords ?? []).filter(
      (item) => !removedCourseIds.has(item.courseId)
    );
    snapshot.value.payments = (snapshot.value.payments ?? []).filter((item) => item.childId !== id);
    snapshot.value.goals = snapshot.value.goals.filter((item) => item.childId !== id);
    snapshot.value.children.splice(childIndex, 1);
    if (snapshot.value.session.childId === id) {
      snapshot.value.session.childId = snapshot.value.children[0].id;
    }
    persist();
    return "removed";
  }
  function selectChild(id) {
    if (!snapshot.value.children.some((item) => item.id === id)) return;
    snapshot.value.session.childId = id;
    persist();
  }
  function findCourse(courseId) {
    return snapshot.value.courses.find((item) => item.id === courseId);
  }
  function findExpense(expenseId) {
    return snapshot.value.expenses.find((item) => item.id === expenseId);
  }
  function ensureBillingCollections() {
    if (!snapshot.value.charges) snapshot.value.charges = [];
    if (!snapshot.value.occurrenceRecords) snapshot.value.occurrenceRecords = [];
    if (!snapshot.value.payments) snapshot.value.payments = [];
  }
  function upsertBilledAdjustment(original, amount, note) {
    var _a;
    ensureBillingCollections();
    const bill = original.billedExpenseId ? findExpense(original.billedExpenseId) : void 0;
    const attachToOpenBill = bill && bill.status !== "paid";
    const adjustments = snapshot.value.charges.filter(
      (item) => item.adjustmentOfChargeId === original.id && item.status !== "reversed"
    );
    const historicalAmount = attachToOpenBill ? 0 : adjustments.filter((item) => item.status === "billed").reduce((sum, item) => sum + item.amount, 0);
    const effectiveAmount = Math.round((amount - historicalAmount) * 100) / 100;
    const existing = adjustments.find(
      (item) => item.status === "unbilled" || attachToOpenBill && item.status === "billed" && item.billedExpenseId === bill.id
    );
    const previousAmount = (existing == null ? void 0 : existing.amount) ?? 0;
    if (effectiveAmount === 0) {
      if ((existing == null ? void 0 : existing.status) === "billed" && bill) {
        bill.amount = Math.max(0, Math.round((bill.amount - previousAmount) * 100) / 100);
        bill.chargeIds = (_a = bill.chargeIds) == null ? void 0 : _a.filter((id) => id !== existing.id);
        bill.status = bill.amount === 0 ? "void" : "unpaid";
      }
      if (existing) existing.status = "reversed";
      return;
    }
    const next = {
      id: (existing == null ? void 0 : existing.id) ?? createId("chg_adjustment"),
      childId: original.childId,
      courseId: original.courseId,
      occurrenceId: original.occurrenceId,
      amount: effectiveAmount,
      status: attachToOpenBill ? "billed" : "unbilled",
      source: "adjustment",
      billedExpenseId: attachToOpenBill ? bill.id : void 0,
      adjustmentOfChargeId: original.id,
      note
    };
    if (attachToOpenBill) {
      bill.amount = Math.max(0, Math.round((bill.amount + effectiveAmount - previousAmount) * 100) / 100);
      bill.chargeIds = [.../* @__PURE__ */ new Set([...bill.chargeIds ?? [], next.id])];
      bill.status = bill.amount === 0 ? "void" : "unpaid";
    }
    if (existing) Object.assign(existing, next);
    else snapshot.value.charges.push(next);
  }
  function waiveUnbilledCharge(occurrenceId) {
    ensureBillingCollections();
    const charge = findChargeForOccurrence(snapshot.value.charges ?? [], occurrenceId);
    if ((charge == null ? void 0 : charge.status) === "unbilled") charge.status = "waived";
    else if ((charge == null ? void 0 : charge.status) === "billed") {
      upsertBilledAdjustment(charge, -charge.amount, "\u8BFE\u6B21\u53D6\u6D88\u51B2\u51CF");
    }
  }
  function upsertUnbilledUsageCharge(course, date, startTime, endTime, actualMinutes) {
    var _a;
    ensureBillingCollections();
    const occurrenceId = occurrenceIdFor(course.id, date);
    const computed2 = expectedUsageCharge(course, startTime, endTime, actualMinutes);
    if (computed2.amount <= 0) {
      waiveUnbilledCharge(occurrenceId);
      return;
    }
    const existing = findChargeForOccurrence(snapshot.value.charges ?? [], occurrenceId);
    if ((existing == null ? void 0 : existing.status) === "billed") {
      upsertBilledAdjustment(
        existing,
        Math.round((computed2.amount - existing.amount) * 100) / 100,
        "\u5DF2\u51FA\u8D26\u8BFE\u6B21\u65F6\u957F\u6216\u8BA1\u4EF7\u8C03\u6574"
      );
      return;
    }
    const next = {
      id: (existing == null ? void 0 : existing.id) ?? createId("chg"),
      childId: ((_a = course.childIds) == null ? void 0 : _a[0]) ?? course.childId,
      courseId: course.id,
      occurrenceId,
      amount: computed2.amount,
      status: "unbilled",
      source: computed2.source,
      estimated: computed2.estimated,
      note: computed2.estimated ? "\u6309\u65F6\u957F\u4F30\u7B97\uFF0C\u786E\u8BA4\u5B9E\u9645\u5206\u949F\u540E\u53EF\u91CD\u7B97" : "\u7531\u5DF2\u5B8C\u6210\u8BFE\u6B21\u81EA\u52A8\u8BA1\u63D0"
    };
    if (existing) {
      const index = snapshot.value.charges.findIndex((item) => item.id === existing.id);
      snapshot.value.charges[index] = { ...existing, ...next, id: existing.id };
    } else {
      snapshot.value.charges.push(next);
    }
  }
  function syncUsageChargeForDate(course, date, startTime, endTime) {
    const occurrenceId = occurrenceIdFor(course.id, date);
    const record = (snapshot.value.occurrenceRecords ?? []).find((item) => item.id === occurrenceId);
    if (shouldAccrueUsage(course, (record == null ? void 0 : record.status) ?? "scheduled", (record == null ? void 0 : record.billable) ?? false)) {
      upsertUnbilledUsageCharge(course, date, startTime, endTime, record == null ? void 0 : record.actualMinutes);
      return;
    }
    waiveUnbilledCharge(occurrenceId);
  }
  function recomputeUnbilledChargesForCourse(course) {
    var _a, _b, _c, _d, _e, _f;
    ensureBillingCollections();
    if (!shouldAccrueUsage(course, "completed", true) && ((_a = course.billingPolicy) == null ? void 0 : _a.pricingMode) !== "per_session" && ((_b = course.billingPolicy) == null ? void 0 : _b.pricingMode) !== "per_hour") {
      for (const charge of snapshot.value.charges ?? []) {
        if (charge.courseId === course.id && charge.status === "unbilled") charge.status = "waived";
      }
      return;
    }
    for (const record of snapshot.value.occurrenceRecords ?? []) {
      if (record.courseId !== course.id) continue;
      const startTime = ((_d = (_c = course.recurrence.dates) == null ? void 0 : _c.find((slot) => slot.date === record.date)) == null ? void 0 : _d.startTime) ?? course.recurrence.startTime;
      const endTime = ((_f = (_e = course.recurrence.dates) == null ? void 0 : _e.find((slot) => slot.date === record.date)) == null ? void 0 : _f.endTime) ?? course.recurrence.endTime;
      syncUsageChargeForDate(course, record.date, startTime, endTime);
    }
  }
  function setOccurrenceAttendance(courseId, date, status, options = {}) {
    var _a;
    const course = findCourse(courseId);
    if (!course) return;
    ensureBillingCollections();
    const occurrenceId = occurrenceIdFor(courseId, date);
    const existingIndex = snapshot.value.occurrenceRecords.findIndex((item) => item.id === occurrenceId);
    const existing = existingIndex >= 0 ? snapshot.value.occurrenceRecords[existingIndex] : void 0;
    const slot = (_a = course.recurrence.dates) == null ? void 0 : _a.find((item) => item.date === date);
    const exception = snapshot.value.scheduleExceptions.find(
      (item) => item.courseId === courseId && item.date === date
    );
    const startTime = (exception == null ? void 0 : exception.startTime) ?? (slot == null ? void 0 : slot.startTime) ?? course.recurrence.startTime;
    const endTime = (exception == null ? void 0 : exception.endTime) ?? (slot == null ? void 0 : slot.endTime) ?? course.recurrence.endTime;
    const billable = options.billable ?? status === "completed";
    const next = {
      id: occurrenceId,
      courseId,
      originDate: (existing == null ? void 0 : existing.originDate) ?? date,
      date,
      status,
      billable,
      actualMinutes: options.actualMinutes ?? (existing == null ? void 0 : existing.actualMinutes),
      confirmedAt: status === "scheduled" ? void 0 : (0, import_dayjs5.default)().format("YYYY-MM-DD")
    };
    if (existingIndex >= 0) snapshot.value.occurrenceRecords[existingIndex] = next;
    else snapshot.value.occurrenceRecords.push(next);
    syncUsageChargeForDate(course, date, startTime, endTime);
    persist();
  }
  function upsertScheduleException(input, options = {}) {
    var _a;
    const course = findCourse(input.courseId);
    const existingIndex = snapshot.value.scheduleExceptions.findIndex(
      (item) => item.courseId === input.courseId && item.date === input.date
    );
    const existing = existingIndex >= 0 ? snapshot.value.scheduleExceptions[existingIndex] : void 0;
    const next = {
      ...existing,
      ...input,
      id: input.id ?? (existing == null ? void 0 : existing.id) ?? createId("exception"),
      childId: (existing == null ? void 0 : existing.childId) ?? ((_a = course == null ? void 0 : course.childIds) == null ? void 0 : _a[0]) ?? (course == null ? void 0 : course.childId) ?? childId.value
    };
    if (existingIndex >= 0) snapshot.value.scheduleExceptions[existingIndex] = next;
    else snapshot.value.scheduleExceptions.push(next);
    if (course) applyExceptionToCourse(course, next);
    if (course) {
      if (next.status === "cancelled") {
        const record = (snapshot.value.occurrenceRecords ?? []).find(
          (item) => item.id === occurrenceIdFor(course.id, next.date)
        );
        if (record) record.status = "cancelled";
        waiveUnbilledCharge(occurrenceIdFor(course.id, next.date));
      } else {
        syncUsageChargeForDate(
          course,
          next.date,
          next.startTime ?? course.recurrence.startTime,
          next.endTime ?? course.recurrence.endTime
        );
      }
    }
    if (options.persist !== false) persist();
    return next;
  }
  function removeScheduleException(courseId, date, options = {}) {
    snapshot.value.scheduleExceptions = snapshot.value.scheduleExceptions.filter(
      (item) => !(item.courseId === courseId && item.date === date)
    );
    if (options.persist !== false) persist();
  }
  function restoreOccurrenceSlot(courseId, slot) {
    const course = findCourse(courseId);
    if (course) restoreCourseSlot(course, slot);
    removeScheduleException(courseId, slot.date, { persist: false });
    const record = (snapshot.value.occurrenceRecords ?? []).find(
      (item) => item.id === occurrenceIdFor(courseId, slot.date)
    );
    if (record && record.status === "cancelled") {
      record.status = "pending_confirmation";
      record.billable = false;
    }
    if (course) syncUsageChargeForDate(course, slot.date, slot.startTime, slot.endTime);
    persist();
  }
  function dropOccurrenceSlot(courseId, date) {
    const course = findCourse(courseId);
    if (course) removeCourseSlot(course, date);
    removeScheduleException(courseId, date, { persist: false });
    waiveUnbilledCharge(occurrenceIdFor(courseId, date));
    persist();
  }
  function clearScheduleExceptionsForCourse(courseId) {
    snapshot.value.scheduleExceptions = snapshot.value.scheduleExceptions.filter(
      (item) => item.courseId !== courseId
    );
    persist();
  }
  function ensurePaymentForExpense(expense) {
    ensureBillingCollections();
    if (expense.status !== "paid") return;
    const existing = snapshot.value.payments.find(
      (payment) => payment.expenseId === expense.id && payment.kind === "payment"
    );
    if (existing) return;
    snapshot.value.payments.push({
      id: createId("pay"),
      childId: expense.childId,
      expenseId: expense.id,
      kind: "payment",
      amount: expense.amount,
      paidAt: expense.paidAt ?? (0, import_dayjs5.default)().format("YYYY-MM-DD"),
      note: "\u8D26\u5355\u786E\u8BA4\u652F\u4ED8"
    });
  }
  function upsertExpense(input) {
    const id = input.id ?? createId("exp");
    const idx = snapshot.value.expenses.findIndex((e) => e.id === id);
    const existing = idx >= 0 ? snapshot.value.expenses[idx] : void 0;
    const ownerChildId = (existing == null ? void 0 : existing.childId) ?? childId.value;
    const next = { ...existing, ...input, id, childId: ownerChildId };
    if ((existing == null ? void 0 : existing.status) === "paid") {
      next.status = "paid";
      next.amount = existing.amount;
      next.paidAt = existing.paidAt;
    }
    if (idx >= 0) snapshot.value.expenses[idx] = next;
    else snapshot.value.expenses.push(next);
    ensurePaymentForExpense(next);
    persist();
    return id;
  }
  function billDueDate(cycle, statementKey) {
    const value = statementKey.slice(statementKey.lastIndexOf(":") + 1);
    if (cycle === "monthly") return (0, import_dayjs5.default)(`${value}-01`).add(1, "month").date(8).format("YYYY-MM-DD");
    if (cycle === "weekly") return (0, import_dayjs5.default)(value).add(13, "day").format("YYYY-MM-DD");
    return (0, import_dayjs5.default)().format("YYYY-MM-DD");
  }
  function generateBillingStatements(period) {
    var _a, _b, _c, _d, _e, _f, _g;
    ensureBillingCollections();
    const created = [];
    const updated = [];
    const records = snapshot.value.occurrenceRecords ?? [];
    const grouped = /* @__PURE__ */ new Map();
    for (const charge of snapshot.value.charges ?? []) {
      if (charge.status !== "unbilled") continue;
      const date = occurrenceDateFromCharge(charge, records);
      if (!date.startsWith(period)) continue;
      const course = findCourse(charge.courseId);
      if (!course || course.needsBillingReview) continue;
      const cycle = (_a = course.billingPolicy) == null ? void 0 : _a.settlementCycle;
      if (!cycle || cycle === "upfront") continue;
      const key = chargeStatementKey(charge, course, records);
      const group = grouped.get(key) ?? { course, charges: [] };
      group.charges.push(charge);
      grouped.set(key, group);
    }
    for (const [baseKey, group] of grouped) {
      const cycle = ((_b = group.course.billingPolicy) == null ? void 0 : _b.settlementCycle) ?? "manual";
      const amount = Math.round(group.charges.reduce((sum, charge) => sum + charge.amount, 0) * 100) / 100;
      if (amount <= 0) continue;
      const existing = snapshot.value.expenses.find(
        (expense) => expense.statementKey === baseKey && expense.status !== "paid"
      );
      const expenseId = (existing == null ? void 0 : existing.id) ?? createId("exp");
      const label = statementLabel(cycle, baseKey);
      if (existing) {
        existing.amount = Math.round((existing.amount + amount) * 100) / 100;
        existing.chargeIds = [.../* @__PURE__ */ new Set([...existing.chargeIds ?? [], ...group.charges.map((item) => item.id)])];
        if (existing.amount > 0) existing.status = "unpaid";
        updated.push(existing.id);
      } else {
        const previousCount = snapshot.value.expenses.filter(
          (expense) => {
            var _a2;
            return (_a2 = expense.statementKey) == null ? void 0 : _a2.startsWith(baseKey);
          }
        ).length;
        const statementKey = previousCount ? `${baseKey}:supplement:${previousCount + 1}` : baseKey;
        snapshot.value.expenses.push({
          id: expenseId,
          childId: ((_c = group.charges[0]) == null ? void 0 : _c.childId) || ((_d = group.course.childIds) == null ? void 0 : _d[0]) || group.course.childId,
          courseId: group.course.id,
          source: "course_usage",
          title: `${group.course.title} \xB7 ${label}\u8BFE\u6B21\u8D39`,
          category: group.course.type,
          billingMode: "session",
          amount,
          period,
          dueDate: billDueDate(cycle, baseKey),
          status: "unpaid",
          note: `${group.charges.length} \u6761\u5F85\u7ED3\u7B97\u660E\u7EC6\u6C47\u603B`,
          chargeIds: group.charges.map((item) => item.id),
          statementKey
        });
        created.push(expenseId);
      }
      for (const charge of group.charges) {
        charge.status = "billed";
        charge.billedExpenseId = expenseId;
      }
    }
    const periodStart = (0, import_dayjs5.default)(`${period}-01`);
    const periodEnd = periodStart.endOf("month");
    for (const course of snapshot.value.courses.filter((item) => !item.archived)) {
      if (course.needsBillingReview || ((_e = course.billingPolicy) == null ? void 0 : _e.pricingMode) !== "fixed_period") continue;
      const cycle = course.billingPolicy.settlementCycle;
      const keys = cycle === "weekly" ? [...new Set(
        Array.from(
          { length: periodStart.daysInMonth() },
          (_, index) => mondayOf(periodStart.date(index + 1).format("YYYY-MM-DD"))
        )
      )] : cycle === "monthly" ? [period] : [];
      for (const value of keys) {
        const rangeStart = cycle === "weekly" ? (0, import_dayjs5.default)(value) : periodStart;
        const rangeEnd = cycle === "weekly" ? rangeStart.add(6, "day") : periodEnd;
        if ((0, import_dayjs5.default)(course.recurrence.startDate).isAfter(rangeEnd, "day")) continue;
        if (course.recurrence.endDate && (0, import_dayjs5.default)(course.recurrence.endDate).isBefore(rangeStart, "day")) continue;
        const statementKey = `${course.id}:fixed:${cycle}:${value}`;
        if (snapshot.value.expenses.some((expense) => expense.statementKey === statementKey)) continue;
        if (cycle === "monthly" && snapshot.value.expenses.some(
          (expense) => expense.courseId === course.id && expense.period === period && expense.billingMode !== "session" && expense.source !== "course_usage"
        )) continue;
        const chargeId = createId("chg");
        const expenseId = createId("exp");
        snapshot.value.charges.push({
          id: chargeId,
          childId: ((_f = course.childIds) == null ? void 0 : _f[0]) ?? course.childId,
          courseId: course.id,
          occurrenceId: `period_${statementKey}`,
          amount: course.amount,
          status: "billed",
          source: "fixed_period",
          billedExpenseId: expenseId,
          note: "\u56FA\u5B9A\u5468\u671F\u8D39\u7528"
        });
        snapshot.value.expenses.push({
          id: expenseId,
          childId: ((_g = course.childIds) == null ? void 0 : _g[0]) ?? course.childId,
          courseId: course.id,
          source: "course_period",
          title: `${course.title} \xB7 ${statementLabel(cycle, statementKey)}\u56FA\u5B9A\u8D39`,
          category: course.type,
          billingMode: cycle === "monthly" ? "monthly" : "session",
          amount: course.amount,
          period,
          dueDate: billDueDate(cycle, statementKey),
          status: "unpaid",
          note: "\u7531\u56FA\u5B9A\u5468\u671F\u8BA1\u8D39\u89C4\u5219\u751F\u6210",
          chargeIds: [chargeId],
          statementKey
        });
        created.push(expenseId);
      }
    }
    persist();
    return { created: created.length, updated: updated.length };
  }
  function monthsOverlapping(from, to) {
    const months = [];
    let cursor = (0, import_dayjs5.default)(from).startOf("month");
    const end = (0, import_dayjs5.default)(to).startOf("month");
    if (!cursor.isValid() || !end.isValid()) return months;
    while (cursor.isBefore(end, "month") || cursor.isSame(end, "month")) {
      months.push(cursor.format("YYYY-MM"));
      cursor = cursor.add(1, "month");
    }
    return months;
  }
  function ensureBillingForRange(from, to) {
    let created = 0;
    let updated = 0;
    for (const period of monthsOverlapping(from, to)) {
      const result = generateBillingStatements(period);
      created += result.created;
      updated += result.updated;
    }
    return { created, updated };
  }
  function syncUnpaidCourseFees(course) {
    var _a, _b, _c;
    if (((_a = course.billingPolicy) == null ? void 0 : _a.pricingMode) === "prepaid" || course.billingMode === "term") return;
    if (((_b = course.billingPolicy) == null ? void 0 : _b.pricingMode) === "free" || course.billingMode === "free") return;
    const unit = roundMoney(course.amount);
    if (unit < 0) return;
    for (const expense of snapshot.value.expenses) {
      if (expense.courseId !== course.id) continue;
      if (expense.status === "paid" || expense.status === "void") continue;
      if (expense.source === "course_upfront") continue;
      if (((_c = course.billingPolicy) == null ? void 0 : _c.pricingMode) === "per_hour") continue;
      expense.amount = unit;
      for (const charge of snapshot.value.charges ?? []) {
        if (charge.billedExpenseId !== expense.id || charge.status === "reversed") continue;
        charge.amount = unit;
      }
    }
    recomputeUnbilledChargesForCourse(course);
  }
  function ensureSessionExpensesForCourse(course) {
    var _a, _b;
    if (((_a = course.billingPolicy) == null ? void 0 : _a.pricingMode) === "free" || course.billingMode === "free") return;
    if (((_b = course.billingPolicy) == null ? void 0 : _b.pricingMode) === "prepaid" || course.billingMode === "term") return;
    if (!isUsagePriced(course) && course.billingMode !== "session") return;
    for (const slot of course.recurrence.dates ?? []) {
      upsertOccurrenceExpense(course.id, slot.date, {
        amount: roundMoney(course.amount),
        paid: false
      });
    }
  }
  function ensureCourseBilling(course) {
    var _a;
    recomputeUnbilledChargesForCourse(course);
    syncUnpaidCourseFees(course);
    ensureSessionExpensesForCourse(course);
    const dates = (((_a = course.recurrence.dates) == null ? void 0 : _a.map((slot) => slot.date)) ?? [course.recurrence.startDate]).filter(Boolean);
    if (dates.length) {
      dates.sort();
      ensureBillingForRange(dates[0], dates[dates.length - 1]);
    }
  }
  function syncCourseUpfrontExpense(courseId, status) {
    var _a, _b, _c;
    const course = findCourse(courseId);
    if (!course) return;
    let existingIndex = snapshot.value.expenses.findIndex(
      (item) => item.courseId === courseId && item.source === "course_upfront"
    );
    if (existingIndex < 0 && ((_a = course.billingPolicy) == null ? void 0 : _a.pricingMode) === "prepaid") {
      const legacyCandidates = snapshot.value.expenses.map((item, index) => ({ item, index })).filter(
        ({ item }) => item.courseId === courseId && !item.source && item.billingMode === "term"
      );
      if (legacyCandidates.length === 1) existingIndex = legacyCandidates[0].index;
    }
    const existing = existingIndex >= 0 ? snapshot.value.expenses[existingIndex] : void 0;
    if (((_b = course.billingPolicy) == null ? void 0 : _b.pricingMode) !== "prepaid") {
      if (existing && existing.status !== "paid") snapshot.value.expenses.splice(existingIndex, 1);
      persist();
      return;
    }
    const paidAt = status === "paid" ? (existing == null ? void 0 : existing.paidAt) ?? (0, import_dayjs5.default)().format("YYYY-MM-DD") : void 0;
    const amount = (existing == null ? void 0 : existing.status) === "paid" && status === "paid" ? existing.amount : Math.max(0, course.amount);
    const next = {
      id: (existing == null ? void 0 : existing.id) ?? createId("exp"),
      childId: ((_c = course.childIds) == null ? void 0 : _c[0]) ?? course.childId,
      courseId,
      source: "course_upfront",
      title: `${course.title} \xB7 \u4E00\u6B21\u6027\u8BFE\u7A0B\u8D39`,
      category: course.type,
      billingMode: "term",
      amount,
      period: (paidAt ?? (0, import_dayjs5.default)().format("YYYY-MM-DD")).slice(0, 7),
      dueDate: paidAt ?? (0, import_dayjs5.default)().format("YYYY-MM-DD"),
      status,
      paidAt,
      note: (existing == null ? void 0 : existing.status) === "paid" && status === "paid" ? existing.note : "\u7531\u8BFE\u7A0B\u4E00\u6B21\u6027\u652F\u4ED8\u8BBE\u7F6E\u540C\u6B65"
    };
    if (existingIndex >= 0) snapshot.value.expenses[existingIndex] = next;
    else snapshot.value.expenses.push(next);
    ensurePaymentForExpense(next);
    persist();
    return next.id;
  }
  function addPresetOccurrence(courseId, date) {
    var _a;
    const course = snapshot.value.courses.find((item) => item.id === courseId);
    if (!course || course.archived) return { ok: false, reason: "invalid" };
    const dates = [...new Set((Array.isArray(date) ? date : [date]).filter(Boolean))].sort();
    if (!dates.length) return { ok: false, reason: "invalid" };
    const sample = (_a = course.recurrence.dates) == null ? void 0 : _a[0];
    const startTime = (sample == null ? void 0 : sample.startTime) ?? course.recurrence.startTime;
    const endTime = (sample == null ? void 0 : sample.endTime) ?? course.recurrence.endTime;
    const pending = dates.filter(
      (day) => !occurrencesOnDate(overviewCourses.value, day, overviewScheduleExceptions.value).some((item) => item.course.id === courseId)
    );
    if (!pending.length) return { ok: false, reason: "duplicate" };
    const [conflict] = findScheduleConflicts(
      pending.map((date2) => ({ date: date2, startTime, endTime })),
      overviewCourses.value,
      overviewScheduleExceptions.value,
      courseId,
      courseParticipantIds(course)
    );
    if (conflict) return { ok: false, reason: "conflict", conflict };
    let added = 0;
    for (const day of pending) {
      upsertScheduleException({
        courseId: course.id,
        date: day,
        status: "added",
        startTime,
        endTime,
        title: course.title,
        location: course.location,
        note: "\u4ECE\u8BFE\u7A0B\u9884\u8BBE\u6DFB\u52A0"
      }, { persist: false });
      added += 1;
    }
    persist();
    if (added) ensureSessionExpensesForCourse(course);
    return added ? { ok: true } : { ok: false, reason: "duplicate" };
  }
  function createQuickArrangement(input) {
    var _a;
    const title = input.title.trim();
    const dates = [...new Set((((_a = input.dates) == null ? void 0 : _a.length) ? input.dates : input.date ? [input.date] : []).filter(Boolean))].sort();
    if (!title || !dates.length || !input.startTime || !input.endTime || input.endTime <= input.startTime) {
      return { ok: false, reason: "invalid" };
    }
    const ownerChildId = childId.value;
    for (const day of dates) {
      const conflict = findBusyConflict(
        busyIntervalsOnDate(
          coursesForParticipants(overviewCourses.value, [ownerChildId]),
          day,
          overviewScheduleExceptions.value
        ),
        input.startTime,
        input.endTime
      );
      if (conflict) return { ok: false, reason: "conflict", conflict };
    }
    const courseId = createId("course");
    const amount = Math.max(0, Number(input.amount) || 0);
    const startDate = dates[0];
    const endDate = dates[dates.length - 1];
    snapshot.value.courses.push({
      id: courseId,
      childId: ownerChildId,
      childIds: [ownerChildId],
      source: "temporary",
      title,
      type: "interest",
      teacher: "",
      location: "",
      icon: "generic",
      color: COURSE_ICON_COLORS.generic,
      billingPolicy: {
        pricingMode: amount > 0 ? "per_session" : "free",
        settlementCycle: "manual"
      },
      needsBillingReview: false,
      billingMode: amount > 0 ? "session" : "free",
      amount,
      recurrence: {
        freq: dates.length === 1 ? "once" : "dates",
        byWeekday: [],
        startDate,
        endDate,
        startTime: input.startTime,
        endTime: input.endTime,
        dates: dates.map((date) => ({ date, startTime: input.startTime, endTime: input.endTime }))
      },
      archived: false,
      note: "\u901A\u8FC7\u5FEB\u901F\u65B0\u589E\u521B\u5EFA\u7684\u4E34\u65F6\u5B89\u6392"
    });
    let expenseId;
    if (amount > 0) {
      expenseId = createId("exp");
      snapshot.value.expenses.push({
        id: expenseId,
        childId: ownerChildId,
        courseId,
        source: "temporary",
        title: `${title} \xB7 \u5355\u6B21\u8D39\u7528`,
        category: "temporary",
        billingMode: "session",
        amount,
        period: startDate.slice(0, 7),
        dueDate: startDate,
        status: input.expenseStatus,
        paidAt: input.expenseStatus === "paid" ? (0, import_dayjs5.default)().format("YYYY-MM-DD") : void 0,
        note: "\u968F\u5FEB\u901F\u65B0\u589E\u5B89\u6392\u521B\u5EFA"
      });
      ensurePaymentForExpense(snapshot.value.expenses[snapshot.value.expenses.length - 1]);
    }
    persist();
    return { ok: true, courseId, expenseId };
  }
  function findOccurrenceExpense(courseId, date) {
    const sameDay = snapshot.value.expenses.find(
      (item) => item.courseId === courseId && item.status !== "void" && item.dueDate === date
    );
    if (sameDay) return sameDay;
    const course = findCourse(courseId);
    if ((course == null ? void 0 : course.source) === "temporary") {
      return snapshot.value.expenses.find((item) => item.courseId === courseId && item.status !== "void");
    }
    return void 0;
  }
  function upsertOccurrenceExpense(courseId, date, input) {
    var _a, _b;
    const course = findCourse(courseId);
    if (!course) return "not-found";
    const amount = Math.round(Math.max(0, Number(input.amount) || 0) * 100) / 100;
    let expense = findOccurrenceExpense(courseId, date);
    if ((expense == null ? void 0 : expense.status) === "paid") return "paid-immutable";
    if (!expense) {
      if (amount <= 0) {
        if (course.source === "temporary") {
          course.amount = 0;
          course.billingMode = "free";
          course.billingPolicy = {
            pricingMode: "free",
            settlementCycle: ((_a = course.billingPolicy) == null ? void 0 : _a.settlementCycle) ?? "manual"
          };
        }
        persist();
        return "cleared";
      }
      const charge = findChargeForOccurrence(snapshot.value.charges ?? [], occurrenceIdFor(courseId, date));
      expense = {
        id: createId("exp"),
        childId: course.childId,
        courseId,
        source: course.source === "temporary" ? "temporary" : "course_usage",
        title: `${course.title} \xB7 \u5355\u6B21\u8D39\u7528`,
        category: course.source === "temporary" ? "temporary" : course.type,
        billingMode: "session",
        amount,
        period: date.slice(0, 7),
        dueDate: date,
        status: "unpaid",
        note: "\u8BFE\u6B21\u8D39\u7528",
        chargeIds: (charge == null ? void 0 : charge.status) === "unbilled" ? [charge.id] : []
      };
      snapshot.value.expenses.push(expense);
      if ((charge == null ? void 0 : charge.status) === "unbilled") {
        charge.status = "billed";
        charge.billedExpenseId = expense.id;
        charge.amount = amount;
      }
    } else if (amount <= 0) {
      const expenseId = expense.id;
      snapshot.value.expenses = snapshot.value.expenses.filter((item) => item.id !== expenseId);
      for (const charge of snapshot.value.charges ?? []) {
        if (charge.billedExpenseId !== expenseId) continue;
        charge.status = charge.source === "fixed_period" ? "reversed" : "unbilled";
        charge.billedExpenseId = void 0;
      }
      expense = void 0;
    } else {
      expense.amount = amount;
    }
    if (course.source === "temporary") {
      course.amount = amount;
      course.billingMode = amount > 0 ? "session" : "free";
      course.billingPolicy = {
        pricingMode: amount > 0 ? "per_session" : "free",
        settlementCycle: ((_b = course.billingPolicy) == null ? void 0 : _b.settlementCycle) ?? "manual"
      };
    }
    if (expense && input.paid && amount > 0) {
      expense.status = "paid";
      expense.paidAt = (0, import_dayjs5.default)().format("YYYY-MM-DD");
      ensurePaymentForExpense(expense);
    }
    persist();
    return "updated";
  }
  function setExpenseStatus(id, status) {
    const item = snapshot.value.expenses.find((e) => e.id === id);
    if (!item) return "not-found";
    if (item.status === "paid" && status !== "paid") return "paid-immutable";
    item.status = status;
    item.paidAt = status === "paid" ? (0, import_dayjs5.default)().format("YYYY-MM-DD") : void 0;
    ensurePaymentForExpense(item);
    persist();
    return "updated";
  }
  function refundExpense(id, amount, note = "") {
    ensureBillingCollections();
    const expense = findExpense(id);
    if (!expense || expense.status !== "paid") return { ok: false, reason: "not-paid" };
    const payment = snapshot.value.payments.find(
      (item) => item.expenseId === id && item.kind === "payment"
    );
    if (!payment) return { ok: false, reason: "payment-missing" };
    const refunded = snapshot.value.payments.filter((item) => item.kind === "refund" && item.refundOfPaymentId === payment.id).reduce((sum, item) => sum + item.amount, 0);
    const value = Math.round(Math.max(0, Number(amount) || 0) * 100) / 100;
    const remaining = Math.round((payment.amount - refunded) * 100) / 100;
    if (value <= 0 || value > remaining) {
      return { ok: false, reason: "invalid-amount", remaining };
    }
    const refund = {
      id: createId("refund"),
      childId: expense.childId,
      expenseId: expense.id,
      kind: "refund",
      amount: value,
      paidAt: (0, import_dayjs5.default)().format("YYYY-MM-DD"),
      refundOfPaymentId: payment.id,
      note: note.trim() || "\u8D26\u5355\u9000\u6B3E"
    };
    snapshot.value.payments.push(refund);
    let unapplied = value;
    for (const adjustment of snapshot.value.charges.filter((charge) => {
      if (charge.status !== "unbilled" || charge.source !== "adjustment") return false;
      const original = charge.adjustmentOfChargeId ? snapshot.value.charges.find((item) => item.id === charge.adjustmentOfChargeId) : void 0;
      return (original == null ? void 0 : original.billedExpenseId) === expense.id && charge.amount < 0;
    })) {
      if (Math.abs(adjustment.amount) > unapplied) continue;
      adjustment.status = "billed";
      adjustment.billedExpenseId = expense.id;
      expense.chargeIds = [.../* @__PURE__ */ new Set([...expense.chargeIds ?? [], adjustment.id])];
      unapplied = Math.round((unapplied - Math.abs(adjustment.amount)) * 100) / 100;
    }
    persist();
    return { ok: true, refundId: refund.id, remaining: Math.round((remaining - value) * 100) / 100 };
  }
  function removeExpense(id) {
    var _a;
    const expense = findExpense(id);
    if (!expense) return "not-found";
    if (expense.status === "paid" || ((_a = snapshot.value.payments) == null ? void 0 : _a.some((item) => item.expenseId === id))) {
      return "paid-immutable";
    }
    for (const charge of snapshot.value.charges ?? []) {
      if (charge.billedExpenseId !== id) continue;
      charge.status = charge.source === "fixed_period" ? "reversed" : "unbilled";
      charge.billedExpenseId = void 0;
    }
    snapshot.value.expenses = snapshot.value.expenses.filter((e) => e.id !== id);
    persist();
    return "removed";
  }
  function addGoalProgress(id, delta) {
    const goal = snapshot.value.goals.find((g) => g.id === id);
    if (!goal) return;
    goal.doneCount = Math.max(0, Math.min(goal.targetCount, goal.doneCount + delta));
    if (goal.doneCount >= goal.targetCount) goal.status = "done";
    persist();
  }
  return {
    snapshot,
    child,
    courses,
    allCourses,
    expenses,
    goals,
    scheduleExceptions,
    isParentSession,
    overviewCourses,
    overviewExpenses,
    overviewScheduleExceptions,
    coursesForChild,
    todayItems,
    monthOpenAmount,
    overviewCharges,
    overviewPayments,
    occurrenceRecords,
    charges,
    payments,
    updateChild,
    addChild,
    removeChild,
    selectChild,
    findCourse,
    findExpense,
    findOccurrenceExpense,
    upsertCourse,
    findCourseScheduleConflicts,
    archiveCourse,
    restoreCourse,
    removeCourse,
    upsertScheduleException,
    removeScheduleException,
    restoreOccurrenceSlot,
    dropOccurrenceSlot,
    clearScheduleExceptionsForCourse,
    upsertExpense,
    syncCourseUpfrontExpense,
    generateBillingStatements,
    ensureBillingForRange,
    ensureCourseBilling,
    addPresetOccurrence,
    createQuickArrangement,
    upsertOccurrenceExpense,
    setOccurrenceAttendance,
    setExpenseStatus,
    refundExpense,
    removeExpense,
    addGoalProgress
  };
}

// cloudfunctions/api/src/index.ts
import_wx_server_sdk.default.init({ env: import_wx_server_sdk.default.DYNAMIC_CURRENT_ENV });
var db = import_wx_server_sdk.default.database();
var users = () => db.collection("users");
var families = () => db.collection("families");
var ActionError = class extends Error {
  code;
  constructor(code, message) {
    super(message);
    this.code = code;
  }
};
function fail(code, message) {
  return { ok: false, code, message };
}
function cloneSnapshot(snapshot) {
  return JSON.parse(JSON.stringify(snapshot));
}
async function findUser(openid) {
  var _a;
  const found = await users().where({ openid }).limit(1).get();
  const user = (_a = found.data) == null ? void 0 : _a[0];
  if (!(user == null ? void 0 : user.familyId)) return null;
  return user;
}
async function requireUser(openid) {
  const user = await findUser(openid);
  if (!user) throw new ActionError("UNAUTHENTICATED", "\u8BF7\u5148\u4F7F\u7528\u5FAE\u4FE1\u767B\u5F55");
  return user;
}
async function withFamily(familyId, apply) {
  return db.runTransaction(async (transaction) => {
    const ref = transaction.collection("families").doc(familyId);
    const got = await ref.get();
    const raw = got.data;
    if (!(raw == null ? void 0 : raw.snapshotJson)) throw new ActionError("FAMILY_MISMATCH", "\u5BB6\u5EAD\u4E0D\u5B58\u5728\u6216\u65E0\u6743\u8BBF\u95EE");
    const workspace = createFamilyWorkspace(JSON.parse(raw.snapshotJson));
    const result = await apply(workspace);
    const nextJson = JSON.stringify(workspace.snapshot.value);
    if (nextJson !== raw.snapshotJson) {
      await ref.update({
        data: {
          snapshotJson: nextJson,
          version: (raw.version || 1) + 1,
          updatedAt: (/* @__PURE__ */ new Date()).toISOString()
        }
      });
    }
    return {
      snapshot: JSON.parse(nextJson),
      result: result ?? null
    };
  });
}
function raiseObject(result) {
  if (!result || typeof result !== "object" || !("ok" in result) || result.ok !== false) return result;
  const reason = "reason" in result ? String(result.reason) : "";
  if (reason === "conflict") throw new ActionError("SCHEDULE_CONFLICT", "\u8BE5\u5B69\u5B50\u6B64\u65F6\u5DF2\u6709\u5176\u4ED6\u8BFE\u7A0B");
  if (reason === "duplicate") throw new ActionError("OCCURRENCE_DUPLICATE", "\u6240\u9009\u65E5\u671F\u90FD\u5DF2\u6709\u8FD9\u95E8\u8BFE");
  if (reason === "invalid-amount") throw new ActionError("REFUND_EXCEEDS_PAYMENT", "\u9000\u6B3E\u91D1\u989D\u5E94\u5927\u4E8E 0\uFF0C\u4E14\u4E0D\u8D85\u8FC7\u5269\u4F59\u53EF\u9000\u91D1\u989D");
  if (reason === "not-paid" || reason === "payment-missing") throw new ActionError("REFUND_NOT_ALLOWED", "\u5F53\u524D\u8D26\u5355\u65E0\u6CD5\u9000\u6B3E");
  throw new ActionError("INVALID_INPUT", "\u8BF7\u5B8C\u6574\u586B\u5199\u540E\u518D\u4FDD\u5B58");
}
function raiseCode(result, map) {
  if (typeof result === "string" && map[result]) {
    const [code, message] = map[result];
    throw new ActionError(code, message);
  }
  return result;
}
function billWindow(payload) {
  const from = typeof payload.from === "string" ? payload.from : (0, import_dayjs6.default)().startOf("month").format("YYYY-MM-DD");
  const to = typeof payload.to === "string" ? payload.to : (0, import_dayjs6.default)().endOf("month").format("YYYY-MM-DD");
  return { from, to };
}
function ensureRange(workspace, from, to) {
  var _a;
  for (const course of workspace.snapshot.value.courses.filter((item) => !item.archived)) {
    const dates = ((_a = course.recurrence.dates) == null ? void 0 : _a.map((slot) => slot.date)) ?? [];
    if (dates.some((date) => date >= from && date <= to)) workspace.ensureCourseBilling(course);
  }
  workspace.ensureBillingForRange(from, to);
}
async function login(openid, unionid, payload) {
  var _a;
  const existing = await findUser(openid);
  if (existing) {
    const { from, to } = billWindow({});
    const data = await withFamily(existing.familyId, (workspace) => {
      ensureRange(workspace, from, to);
      return null;
    });
    return { openid, familyId: existing.familyId, snapshot: data.snapshot };
  }
  const childName = String(payload.childName || "").trim().slice(0, 20);
  const snapshot = createEmptyFamilySnapshot(childName || "\u5C0F\u6811");
  const created = await families().add({
    data: {
      name: `${((_a = snapshot.children[0]) == null ? void 0 : _a.name) || "\u5C0F\u6811"}\u7684\u5BB6\u5EAD`,
      timezone: "Asia/Shanghai",
      ownerOpenid: openid,
      snapshotJson: JSON.stringify(snapshot),
      version: 1,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      updatedAt: (/* @__PURE__ */ new Date()).toISOString()
    }
  });
  const familyId = String(created._id || created.id || "");
  if (!familyId) throw new ActionError("CLOUD_ERROR", "\u521B\u5EFA\u5BB6\u5EAD\u5931\u8D25");
  await users().add({
    data: {
      openid,
      unionid,
      familyId,
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    }
  });
  return { openid, familyId, snapshot: cloneSnapshot(snapshot) };
}
async function dispatch(openid, action, payload) {
  const user = await requireUser(openid);
  const familyId = user.familyId;
  switch (action) {
    case "snapshot":
      return withFamily(familyId, (workspace) => {
        const { from, to } = billWindow(payload);
        ensureRange(workspace, from, to);
        return null;
      });
    case "addChild":
      return withFamily(familyId, (workspace) => {
        const id = workspace.addChild(String(payload.name || ""), payload.avatarKey);
        if (!id) throw new ActionError("INVALID_CHILD_NAME", "\u8BF7\u5148\u586B\u5199\u5B69\u5B50\u540D\u5B57");
        return id;
      });
    case "updateChild":
      return withFamily(familyId, (workspace) => {
        workspace.updateChild({
          id: String(payload.id || ""),
          name: typeof payload.name === "string" ? payload.name : void 0,
          avatarKey: payload.avatarKey
        });
        return null;
      });
    case "removeChild":
      return withFamily(familyId, (workspace) => raiseCode(workspace.removeChild(String(payload.id || "")), {
        "not-found": ["CHILD_NOT_FOUND", "\u8BE5\u5B69\u5B50\u5DF2\u4E0D\u5B58\u5728"],
        "last-child": ["LAST_CHILD_NOT_DELETABLE", "\u81F3\u5C11\u9700\u8981\u4FDD\u7559\u4E00\u4E2A\u5B69\u5B50"]
      }));
    case "selectChild":
      return withFamily(familyId, (workspace) => {
        const childId = String(payload.childId || "");
        if (!workspace.snapshot.value.children.some((item) => item.id === childId)) {
          throw new ActionError("CHILD_NOT_FOUND", "\u5B69\u5B50\u4E0D\u5B58\u5728");
        }
        workspace.selectChild(childId);
        return childId;
      });
    case "saveCourse":
      return withFamily(familyId, (workspace) => {
        var _a, _b, _c;
        const course = payload.course;
        if (!((_a = course == null ? void 0 : course.title) == null ? void 0 : _a.trim()) || !((_c = (_b = course.recurrence) == null ? void 0 : _b.dates) == null ? void 0 : _c.length)) {
          throw new ActionError("INVALID_INPUT", "\u8BF7\u586B\u5199\u8BFE\u7A0B\u540D\u79F0\u5E76\u81F3\u5C11\u9009\u62E9\u4E00\u4E2A\u4E0A\u8BFE\u65E5\u671F");
        }
        const dates = course.recurrence.dates;
        const [conflict] = workspace.findCourseScheduleConflicts(dates, course.id, course.childIds);
        if (conflict) throw new ActionError("SCHEDULE_CONFLICT", `\u4E0E\u300C${conflict.title}\u300D\u65F6\u95F4\u91CD\u53E0`);
        const id = workspace.upsertCourse(course);
        const paymentStatus = payload.paymentStatus === "paid" ? "paid" : "unpaid";
        workspace.syncCourseUpfrontExpense(id, paymentStatus);
        workspace.clearScheduleExceptionsForCourse(id);
        return id;
      });
    case "archiveCourse":
      return withFamily(familyId, (workspace) => workspace.archiveCourse(String(payload.id || "")));
    case "restoreCourse":
      return withFamily(familyId, (workspace) => workspace.restoreCourse(String(payload.id || "")));
    case "removeCourse":
      return withFamily(familyId, (workspace) => raiseCode(workspace.removeCourse(String(payload.id || "")), {
        "not-found": ["COURSE_NOT_FOUND", "\u8BFE\u7A0B\u4E0D\u5B58\u5728"]
      }));
    case "addOccurrences":
      return withFamily(familyId, (workspace) => raiseObject(
        workspace.addPresetOccurrence(String(payload.courseId || ""), payload.dates)
      ));
    case "quickArrangement":
      return withFamily(familyId, (workspace) => raiseObject(workspace.createQuickArrangement({
        dates: payload.dates,
        date: typeof payload.date === "string" ? payload.date : void 0,
        title: String(payload.title || ""),
        startTime: String(payload.startTime || ""),
        endTime: String(payload.endTime || ""),
        amount: Number(payload.amount) || 0,
        expenseStatus: payload.expenseStatus === "paid" ? "paid" : "unpaid"
      })));
    case "upsertException":
      return withFamily(familyId, (workspace) => workspace.upsertScheduleException(payload));
    case "restoreOccurrence":
      return withFamily(familyId, (workspace) => workspace.restoreOccurrenceSlot(String(payload.courseId || ""), {
        date: String(payload.date || ""),
        startTime: String(payload.startTime || ""),
        endTime: String(payload.endTime || "")
      }));
    case "dropOccurrence":
      return withFamily(familyId, (workspace) => {
        workspace.dropOccurrenceSlot(String(payload.courseId || ""), String(payload.date || ""));
        return null;
      });
    case "attendance":
      return withFamily(familyId, (workspace) => workspace.setOccurrenceAttendance(
        String(payload.courseId || ""),
        String(payload.date || ""),
        payload.status,
        {
          billable: Boolean(payload.billable),
          actualMinutes: payload.actualMinutes == null ? void 0 : Number(payload.actualMinutes)
        }
      ));
    case "occurrenceExpense":
      return withFamily(familyId, (workspace) => raiseCode(
        workspace.upsertOccurrenceExpense(String(payload.courseId || ""), String(payload.date || ""), {
          amount: Number(payload.amount) || 0,
          paid: Boolean(payload.paid)
        }),
        {
          "not-found": ["COURSE_NOT_FOUND", "\u8BFE\u7A0B\u4E0D\u5B58\u5728"],
          "paid-immutable": ["PAID_BILL_IMMUTABLE", "\u5DF2\u652F\u4ED8\u8D26\u5355\u4E0D\u80FD\u6539\u91D1\u989D"]
        }
      ));
    case "upsertExpense":
      return withFamily(familyId, (workspace) => workspace.upsertExpense(payload));
    case "generateBills":
      return withFamily(familyId, (workspace) => {
        const period = String(payload.period || "");
        if (!/^\d{4}-\d{2}$/.test(period)) throw new ActionError("INVALID_PERIOD", "\u8D26\u671F\u683C\u5F0F\u5E94\u4E3A YYYY-MM");
        return workspace.generateBillingStatements(period);
      });
    case "setExpenseStatus":
      return withFamily(familyId, (workspace) => raiseCode(
        workspace.setExpenseStatus(String(payload.id || ""), payload.status),
        {
          "not-found": ["BILL_NOT_FOUND", "\u8D26\u5355\u4E0D\u5B58\u5728"],
          "paid-immutable": ["PAID_BILL_IMMUTABLE", "\u5DF2\u652F\u4ED8\u8D26\u5355\u4E0D\u80FD\u6539\u56DE\u672A\u652F\u4ED8"]
        }
      ));
    case "refund":
      return withFamily(familyId, (workspace) => raiseObject(
        workspace.refundExpense(String(payload.id || ""), Number(payload.amount) || 0, String(payload.note || ""))
      ));
    case "removeExpense":
      return withFamily(familyId, (workspace) => raiseCode(workspace.removeExpense(String(payload.id || "")), {
        "not-found": ["BILL_NOT_FOUND", "\u8D26\u5355\u4E0D\u5B58\u5728"],
        "paid-immutable": ["PAID_BILL_IMMUTABLE", "\u5DF2\u652F\u4ED8\u8D26\u5355\u4E0D\u80FD\u5220\u9664"]
      }));
    default:
      throw new ActionError("UNKNOWN_ACTION", "\u4E0D\u652F\u6301\u7684\u64CD\u4F5C");
  }
}
async function main(event) {
  const context = import_wx_server_sdk.default.getWXContext();
  const openid = context.OPENID || "";
  if (!openid) return fail("UNAUTHENTICATED", "\u8BF7\u5728\u5FAE\u4FE1\u5185\u6253\u5F00\u5C0F\u7A0B\u5E8F");
  try {
    const action = (event == null ? void 0 : event.action) || "";
    if (action === "login") {
      const data2 = await login(openid, context.UNIONID || "", event.payload ?? {});
      return { ok: true, data: data2 };
    }
    const data = await dispatch(openid, action, event.payload ?? {});
    return { ok: true, data };
  } catch (error) {
    const code = error instanceof ActionError ? error.code : "CLOUD_ERROR";
    const message = error instanceof Error ? error.message : "\u4E91\u51FD\u6570\u6267\u884C\u5931\u8D25";
    return fail(code, message);
  }
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  main
});
