import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

await esbuild.build({
  entryPoints: [path.join(root, 'cloudfunctions/api/src/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node16',
  format: 'cjs',
  outfile: path.join(root, 'cloudfunctions/api/index.js'),
  external: ['wx-server-sdk'],
  banner: {
    js: '/* Generated by npm run build:cloud. Edit cloudfunctions/api/src and rebuild. */',
  },
})

console.log('cloud function bundled to cloudfunctions/api/index.js')
